spring:
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
          filters:
            - AuthenticationFilter


        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stock/**
          filters:
            - AuthenticationFilter

        - id: iam-service
          uri: lb://IAM-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: APP-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/